#!/usr/bin/env python3
"""Phase C comprehensive encoder × downstream comparison.

Encoders (rows):
  iTransformer (B1 winner W6_d7_K4), MLP-AE, SVD, Linear-AE, Windowed-PCA, Raw-PCA

Downstreams (sub-rows per encoder):
  pca_kmeans, pca_hdbscan, umap_kmeans, umap_hdbscan,
  tsne_kmeans, tsne_hdbscan, pca_gmm  (GMM = new downstream from literature)

Metrics:
  Internal: DBCV, silhouette, n_clusters, noise_fraction
  NBER: frozen F1, legacy max-F1
  Bai-Perron internal: structural-break F1 on PC1 of test signal
  Phase C external (all 6 downstream cells):
    C1: Sahm F1, CFNAI-MA3 F1, Chauvet-Piger F1
    C3: INDPRO PELT F1, PAYEMS PELT F1
  C4: Bootstrap ARI (Ben-Hur 2002, per downstream cell)

Usage:
    cd tcc_ai
    source ../tcc.env
    uv run python scripts/run_phase_c_comparison.py

Runtime: ~10-15 minutes (t-SNE dominates, GMM + MLP-AE training ~2 min each).
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yaml
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA, TruncatedSVD
from sklearn.metrics import silhouette_score
from sklearn.mixture import GaussianMixture

# ── project root on PYTHONPATH ──────────────────────────────────────────────
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from tcc_itransformer.evaluation.panel_metrics import PANEL_COLUMNS, compute_panel_metrics
from tcc_itransformer.pipelines.clustering_ablation import run_ablation
from tcc_itransformer.pipelines.falsification import (
    LinearAE,
    MlpAE,
    Splits,
    _build_splits,
    _encode,
    _train_ae,
)
from tcc_itransformer.pipelines.multi_label import run_multi_label
from tcc_itransformer.pipelines.bai_perron_headline import run_bai_perron_headline
from tcc_itransformer.pipelines.cluster_stability import run_cluster_stability

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ── paths ────────────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "configs/sagemaker_ae_only_W6_d7_K4_b1.yaml"
USREC_CSV = ROOT / "data/snapshots/nber_usrec.csv"
ITR_EMB_DIR = ROOT / "results/sm_outputs/itransformer-1777581449-0d38/embeddings"
ITR_ABLATION_DIR = ROOT / "results/clustering_ablation/W6_d7_K4_b1"
OUT_ROOT = ROOT / "results/phase_c_comparison"
PHASE_E_ROOT = ROOT / "results/phase_e"
FRED_API_KEY = os.environ.get("FRED_API_KEY")
D_LAT = 7  # match iTransformer latent dim

# Phase E encoder names — embeddings + ablation pre-generated by run_phase_e_encoders.py
PHASE_E_NAMES: frozenset[str] = frozenset({
    "moment", "ts2vec", "patchtst", "timesnet", "tfc", "hamilton_hmm", "bocpd",
})


# ── helpers ──────────────────────────────────────────────────────────────────

def _save_z_parquets(
    Z_tr: np.ndarray,
    Z_va: np.ndarray,
    Z_te: np.ndarray,
    train_dates: pd.DatetimeIndex,
    val_dates: pd.DatetimeIndex,
    test_dates: pd.DatetimeIndex,
    out_dir: Path,
) -> None:
    """Save Z_train/val/test.parquet in the format expected by run_ablation."""
    d = Z_tr.shape[1]
    cols = [f"z_{i}" for i in range(d)]
    out_dir.mkdir(parents=True, exist_ok=True)
    for Z, dates, name in [
        (Z_tr, train_dates, "train"),
        (Z_va, val_dates, "val"),
        (Z_te, test_dates, "test"),
    ]:
        df = pd.DataFrame(Z.astype(np.float32), columns=cols)
        df.insert(0, "date", dates)
        df.to_parquet(out_dir / f"Z_{name}.parquet", index=False)


def _add_gmm_downstream(
    emb_dir: Path,
    output_dir: Path,
    n_clusters: int = 4,
    seed: int = 42,
) -> dict:
    """Fit PCA(2) + GaussianMixture(K=n_clusters) and return metrics row.

    GMM extends KMeans by allowing ellipsoidal clusters with full covariance,
    which better captures the varying volatility of macroeconomic regimes.
    Supports predict() for out-of-sample assignment (unlike SpectralClustering).
    Reference: Reynolds (2009) 'Gaussian Mixture Models', Encyclopedia of
    Biometrics; commonly used in macroeconomic regime-switching literature.
    """
    def load_split(name: str) -> tuple[pd.DatetimeIndex, np.ndarray]:
        df = pd.read_parquet(emb_dir / f"Z_{name}.parquet")
        return pd.DatetimeIndex(df["date"]), df.filter(like="z_").to_numpy(dtype=np.float32)

    train_dates, Z_tr = load_split("train")
    val_dates, Z_va = load_split("val")
    test_dates, Z_te = load_split("test")

    pca = PCA(n_components=2, random_state=seed)
    Y_tr = pca.fit_transform(Z_tr)
    Y_va = pca.transform(Z_va)
    Y_te = pca.transform(Z_te)

    gmm = GaussianMixture(
        n_components=n_clusters,
        covariance_type="full",
        n_init=5,
        random_state=seed,
    )
    gmm.fit(Y_tr)

    val_labels = gmm.predict(Y_va).astype(np.int32)
    test_labels = gmm.predict(Y_te).astype(np.int32)
    test_probs = gmm.predict_proba(Y_te).max(axis=1).astype(np.float32)

    # Save parquet (same schema as run_ablation outputs)
    pd.DataFrame({
        "date": test_dates,
        "label": test_labels,
        "probability": test_probs,
        "x_2d": Y_te[:, 0].astype(np.float32),
        "y_2d": Y_te[:, 1].astype(np.float32),
    }).to_parquet(output_dir / "pca_gmm.parquet", index=False)

    panel = compute_panel_metrics(
        val_labels=val_labels,
        val_dates=val_dates,
        test_labels=test_labels,
        test_dates=test_dates,
        Y_test=Y_te,
        test_signal=Y_te,
        usrec_csv=USREC_CSV,
        is_density_clusterer=False,
    )

    mask = test_labels != -1
    sil = (
        float(silhouette_score(Y_te[mask], test_labels[mask]))
        if mask.sum() >= 4 and len(set(test_labels[mask])) >= 2
        else float("nan")
    )
    n_unique = int(len(set(test_labels[test_labels != -1])))

    return {
        "cell": "pca_gmm",
        "dr": "pca",
        "clusterer": "gmm (new)",
        **{k: panel.get(k, float("nan")) for k in PANEL_COLUMNS},
        "test_silhouette": sil,
        "n_clusters_test": n_unique,
        "nber_precision": panel.get("nber_precision", float("nan")),
        "nber_recall": panel.get("nber_recall", float("nan")),
        "nber_assignment": panel.get("nber_assignment", ""),
    }


def _run_external_validity(
    encoder_name: str,
    ablation_dir: Path,
    cell: str = "pca_kmeans",
) -> dict:
    """Run C1 (multi-label) and C3 (Bai-Perron headline) on the given downstream cell parquet.

    Returns flat dict of external metrics.
    """
    parquet = ablation_dir / f"{cell}.parquet"
    if not parquet.exists():
        logger.warning("[%s] %s.parquet not found, skipping C1/C3", encoder_name, cell)
        return {}

    ext: dict = {}

    # C1: multi-label panel
    c1_out = ablation_dir / f"c1_multi_label_{cell}.csv"
    try:
        df_c1 = run_multi_label(parquet, USREC_CSV, c1_out, fred_api_key=FRED_API_KEY)
        # multi_label CSV uses column "label" (not "indicator")
        label_col = "label" if "label" in df_c1.columns else "indicator"
        indicator_map = {
            "sahm": "c1_sahm_f1",
            "cfnai_ma3": "c1_cfnai_f1",
            "chauvet_piger": "c1_chauvet_f1",
            "oecd_cli": "c1_oecd_f1",
        }
        for _, row in df_c1.iterrows():
            key = indicator_map.get(row[label_col])
            if key:
                ext[key] = round(float(row["f1"]), 4) if pd.notna(row["f1"]) else float("nan")
        logger.info("[%s] C1: sahm=%.3f cfnai=%.3f", encoder_name,
                    ext.get("c1_sahm_f1", float("nan")), ext.get("c1_cfnai_f1", float("nan")))
    except Exception as exc:
        logger.warning("[%s] C1 failed: %s", encoder_name, exc)

    # C3: Bai-Perron headline
    c3_out = ablation_dir / f"c3_bai_perron_{cell}.csv"
    try:
        df_c3 = run_bai_perron_headline(parquet, c3_out, fred_api_key=FRED_API_KEY)
        series_map = {
            "INDPRO": "c3_indpro_f1",
            "PAYEMS": "c3_payems_f1",
            "UNRATE": "c3_unrate_f1",
        }
        for _, row in df_c3.iterrows():
            key = series_map.get(row["series"])
            if key:
                ext[key] = round(float(row["pelt_f1"]), 4) if pd.notna(row["pelt_f1"]) else float("nan")
        logger.info("[%s] C3: indpro=%.3f payems=%.3f", encoder_name,
                    ext.get("c3_indpro_f1", float("nan")), ext.get("c3_payems_f1", float("nan")))
    except Exception as exc:
        logger.warning("[%s] C3 failed: %s", encoder_name, exc)

    return ext


def _run_stability(
    encoder_name: str,
    ablation_dir: Path,
    emb_dir: Path,
    n_bootstrap: int = 100,
    pipeline: str = "pca_kmeans",
) -> float:
    """Run C4 Ben-Hur bootstrap stability. Returns overall ARI for the given pipeline.

    Runs run_cluster_stability once per encoder (covers all pipelines) and
    caches the result in c4_stability.csv.  Subsequent calls for different
    pipelines of the same encoder simply read from the cached file.
    """
    c4_out = ablation_dir / "c4_stability.csv"

    def _read_ari(path: Path, pl: str) -> float:
        df = pd.read_csv(path)
        row = df[(df["pipeline"] == pl) & (df["cluster"] == "all") & (df["metric"] == "ari")]
        return float(row["mean_value"].iloc[0]) if not row.empty else float("nan")

    # Use cached result if available
    if c4_out.exists():
        try:
            ari = _read_ari(c4_out, pipeline)
            logger.info("[%s/%s] C4 (cached) ARI=%.3f", encoder_name, pipeline, ari)
            return ari
        except Exception:
            pass  # fall through to recompute

    try:
        df_c4 = run_cluster_stability(
            ablation_dir=ablation_dir,
            emb_dir=emb_dir,
            output=c4_out,
            n_bootstrap=n_bootstrap,
            resample_frac=0.8,
            seed=42,
        )
        ari_row = df_c4[
            (df_c4["pipeline"] == pipeline) &
            (df_c4["cluster"] == "all") &
            (df_c4["metric"] == "ari")
        ]
        if not ari_row.empty:
            ari = float(ari_row["mean_value"].iloc[0])
            logger.info("[%s/%s] C4 ARI=%.3f", encoder_name, pipeline, ari)
            return ari
    except Exception as exc:
        logger.warning("[%s/%s] C4 failed: %s", encoder_name, pipeline, exc)
    return float("nan")


def _generate_encoder_embeddings(
    encoder_name: str,
    sp: Splits,
    d_lat: int,
    seed: int = 42,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Train encoder and return (Z_train, Z_val, Z_test) latent embeddings."""
    in_dim = sp.Z_train_in.shape[1]
    cfg = yaml.safe_load(CONFIG.read_text())
    W = int(cfg["window_size"])
    F = in_dim // W

    if encoder_name == "windowed_pca":
        pca = PCA(n_components=d_lat, random_state=seed)
        Z_tr = pca.fit_transform(sp.Z_train_in)
        Z_va = pca.transform(sp.Z_val_in)
        Z_te = pca.transform(sp.Z_test_in)
        var = pca.explained_variance_ratio_.sum()
        logger.info("[windowed_pca] variance explained: %.1f%%", var * 100)

    elif encoder_name == "raw_pca":
        # PCA on last timestep only (single time step, not windowed)
        tr_last = sp.Z_train_in.reshape(-1, W, F)[:, -1, :]
        va_last = sp.Z_val_in.reshape(-1, W, F)[:, -1, :]
        te_last = sp.Z_test_in.reshape(-1, W, F)[:, -1, :]
        pca = PCA(n_components=min(d_lat, F), random_state=seed)
        Z_tr = pca.fit_transform(tr_last)
        Z_va = pca.transform(va_last)
        Z_te = pca.transform(te_last)
        var = pca.explained_variance_ratio_.sum()
        logger.info("[raw_pca] variance explained: %.1f%%", var * 100)

    elif encoder_name == "linear_ae":
        model = LinearAE(in_dim, d_lat)
        model = _train_ae(model, sp.Z_train_in, epochs=100, seed=seed)
        Z_tr = _encode(model, sp.Z_train_in)
        Z_va = _encode(model, sp.Z_val_in)
        Z_te = _encode(model, sp.Z_test_in)

    elif encoder_name == "mlp_ae":
        model = MlpAE(in_dim, d_lat)
        model = _train_ae(model, sp.Z_train_in, epochs=200, seed=seed)
        Z_tr = _encode(model, sp.Z_train_in)
        Z_va = _encode(model, sp.Z_val_in)
        Z_te = _encode(model, sp.Z_test_in)

    elif encoder_name == "svd":
        svd = TruncatedSVD(n_components=d_lat, random_state=seed)
        Z_tr = svd.fit_transform(sp.Z_train_in)
        Z_va = svd.transform(sp.Z_val_in)
        Z_te = svd.transform(sp.Z_test_in)
        logger.info("[svd] singular values: %s", svd.singular_values_.round(2))

    else:
        raise ValueError(f"Unknown encoder: {encoder_name!r}")

    return Z_tr, Z_va, Z_te


# ── main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    # Ensure relative paths in configs resolve correctly regardless of cwd
    os.chdir(ROOT)

    OUT_ROOT.mkdir(parents=True, exist_ok=True)

    logger.info("Loading data splits from %s", CONFIG)
    sp = _build_splits(yaml.safe_load(CONFIG.read_text()))
    logger.info(
        "Splits: train=%s  val=%s  test=%s  in_dim=%d",
        sp.Z_train_in.shape, sp.Z_val_in.shape, sp.Z_test_in.shape,
        sp.Z_train_in.shape[1],
    )

    # ── encoders to run ───────────────────────────────────────────────────────
    ENCODERS = [
        ("iTransformer", None),    # use existing ablation
        ("windowed_pca", True),
        ("raw_pca", True),
        ("linear_ae", True),
        ("mlp_ae", True),
        ("svd", True),
        # Phase E — embeddings + ablation already generated
        ("moment", None),
        ("ts2vec", None),
        ("patchtst", None),
        ("timesnet", None),
        ("tfc", None),
        ("hamilton_hmm", None),
        ("bocpd", None),
    ]

    all_summary_rows: list[dict] = []
    external_rows: list[dict] = []   # C1/C3/C4 — one per encoder

    for encoder_name, needs_training in ENCODERS:
        logger.info("=" * 60)
        logger.info("ENCODER: %s", encoder_name)

        if encoder_name == "iTransformer":
            ablation_dir = ITR_ABLATION_DIR
            emb_dir = ITR_EMB_DIR
            summary_csv = ablation_dir / "summary.csv"
            if not summary_csv.exists():
                logger.error("iTransformer summary.csv not found at %s", summary_csv)
                continue
            summary = pd.read_csv(summary_csv)
            # Copy existing C4 stability result into the ablation dir for consistency
            existing_c4 = ROOT / "results/diagnostics/cluster_stability.csv"
            itr_c4_dest = ITR_ABLATION_DIR / "c4_stability.csv"
            if existing_c4.exists() and not itr_c4_dest.exists():
                import shutil
                shutil.copy2(existing_c4, itr_c4_dest)
        elif encoder_name in PHASE_E_NAMES:
            ablation_dir = PHASE_E_ROOT / encoder_name / "ablation"
            emb_dir = PHASE_E_ROOT / encoder_name / "embeddings"
            summary_csv = ablation_dir / "summary.csv"
            if not summary_csv.exists():
                logger.error("[%s] Phase E summary.csv not found at %s", encoder_name, summary_csv)
                continue
            summary = pd.read_csv(summary_csv)
        else:
            ablation_dir = OUT_ROOT / encoder_name
            emb_dir = OUT_ROOT / encoder_name / "emb"
            ablation_dir.mkdir(parents=True, exist_ok=True)
            summary_csv = ablation_dir / "summary.csv"

            # Generate + save embeddings (skip if already done)
            if not emb_dir.joinpath("Z_test.parquet").exists():
                logger.info("[%s] Generating embeddings …", encoder_name)
                Z_tr, Z_va, Z_te = _generate_encoder_embeddings(encoder_name, sp, D_LAT)
                _save_z_parquets(Z_tr, Z_va, Z_te,
                                  sp.train_dates, sp.val_dates, sp.test_dates,
                                  emb_dir)
            else:
                logger.info("[%s] Embeddings already exist, skipping.", encoder_name)

            # Run ablation (6 dim-red × clusterer combos)
            if not summary_csv.exists():
                logger.info("[%s] Running clustering ablation …", encoder_name)
                summary = run_ablation(
                    emb_dir, ablation_dir,
                    n_clusters=4, seed=42,
                    usrec_csv=USREC_CSV,
                    methods_dr=("pca", "umap", "tsne"),
                    methods_cl=("kmeans", "hdbscan"),
                    n_perm=0, n_boot=0,   # skip permutation tests for speed
                )
            else:
                logger.info("[%s] summary.csv exists, loading.", encoder_name)
                summary = pd.read_csv(summary_csv)

        # Add GMM downstream (pca_gmm) to every encoder
        gmm_parquet = ablation_dir / "pca_gmm.parquet"
        if not gmm_parquet.exists():
            logger.info("[%s] Computing PCA+GMM downstream …", encoder_name)
            gmm_row = _add_gmm_downstream(emb_dir, ablation_dir, n_clusters=4, seed=42)
        else:
            # Re-compute metrics (parquet exists, avoid re-generating)
            logger.info("[%s] pca_gmm.parquet exists, recomputing metrics.", encoder_name)
            gmm_row = _add_gmm_downstream(emb_dir, ablation_dir, n_clusters=4, seed=42)

        # Append encoder name to summary rows
        for _, row in summary.iterrows():
            all_summary_rows.append({"encoder": encoder_name, **row.to_dict()})

        all_summary_rows.append({"encoder": encoder_name, **gmm_row})

        # ── Phase C external tests — all downstream cells ────────────────────
        CELLS = [
            "pca_kmeans", "pca_hdbscan",
            "umap_kmeans", "umap_hdbscan",
            "tsne_kmeans", "tsne_hdbscan",
        ]
        for cell in CELLS:
            if not (ablation_dir / f"{cell}.parquet").exists():
                continue
            logger.info("[%s] Running C1/C3 external validity on %s …", encoder_name, cell)
            ext = _run_external_validity(encoder_name, ablation_dir, cell=cell)

            logger.info("[%s] Running C4 bootstrap stability for %s …", encoder_name, cell)
            c4_ari = _run_stability(encoder_name, ablation_dir, emb_dir,
                                    n_bootstrap=100, pipeline=cell)

            external_rows.append({
                "encoder": encoder_name,
                "cell": cell,
                **ext,
                "c4_ari": round(c4_ari, 4) if not np.isnan(c4_ari) else float("nan"),
            })

    # ── compile unified table ─────────────────────────────────────────────────
    summary_df = pd.DataFrame(all_summary_rows)

    # Post-hoc: re-read C1 CSVs from disk to recover any in-memory parse failures
    _c1_label_map = {
        "sahm": "c1_sahm_f1",
        "cfnai_ma3": "c1_cfnai_f1",
        "chauvet_piger": "c1_chauvet_f1",
        "oecd_cli": "c1_oecd_f1",
    }
    for enc_row in external_rows:
        enc = enc_row["encoder"]
        cell = enc_row["cell"]
        if enc == "iTransformer":
            c1_csv = ITR_ABLATION_DIR / f"c1_multi_label_{cell}.csv"
        elif enc in PHASE_E_NAMES:
            c1_csv = PHASE_E_ROOT / enc / "ablation" / f"c1_multi_label_{cell}.csv"
        else:
            c1_csv = OUT_ROOT / enc / f"c1_multi_label_{cell}.csv"
        if c1_csv.exists():
            df_c1 = pd.read_csv(c1_csv)
            label_col = "label" if "label" in df_c1.columns else "indicator"
            for _, row in df_c1.iterrows():
                key = _c1_label_map.get(row[label_col])
                if key and (key not in enc_row or pd.isna(enc_row.get(key, float("nan")))):
                    enc_row[key] = round(float(row["f1"]), 4) if pd.notna(row["f1"]) else float("nan")

    external_df = pd.DataFrame(external_rows)

    # Keep only relevant columns from the ablation summary
    keep_cols = [
        "encoder", "cell", "clusterer",
        "dbcv", "test_silhouette", "n_clusters_test", "noise_fraction_test",
        "nber_f1", "nber_f1_legacy_maxF1", "bai_perron_f1",
        "nber_precision", "nber_recall",
    ]
    available = [c for c in keep_cols if c in summary_df.columns]
    table = summary_df[available].copy()

    # Merge external metrics on (encoder, cell) — all downstream cells now have C1/C3/C4
    table = table.merge(external_df, on=["encoder", "cell"], how="left")

    # Round floats
    float_cols = table.select_dtypes(include=[float]).columns
    table[float_cols] = table[float_cols].round(4)

    # Sort: encoder first, then pca_kmeans on top, then rest alphabetically
    cell_order = {
        "pca_kmeans": 0, "pca_hdbscan": 1, "pca_gmm": 2,
        "umap_kmeans": 3, "umap_hdbscan": 4,
        "tsne_kmeans": 5, "tsne_hdbscan": 6,
    }
    encoder_order = {
        "iTransformer": 0, "windowed_pca": 1, "raw_pca": 2,
        "linear_ae": 3, "mlp_ae": 4, "svd": 5,
        "moment": 6, "ts2vec": 7, "patchtst": 8,
        "timesnet": 9, "tfc": 10, "hamilton_hmm": 11, "bocpd": 12,
    }
    table["_enc_ord"] = table["encoder"].map(encoder_order).fillna(99)
    table["_cell_ord"] = table["cell"].map(cell_order).fillna(9)
    table = table.sort_values(["_enc_ord", "_cell_ord"]).drop(columns=["_enc_ord", "_cell_ord"])
    table = table.reset_index(drop=True)

    # Save full table
    out_csv = OUT_ROOT / "phase_c_comparison.csv"
    table.to_csv(out_csv, index=False)
    logger.info("Full table written to %s", out_csv)

    # ── print summary view ────────────────────────────────────────────────────
    print("\n" + "=" * 100)
    print("PHASE C COMPREHENSIVE COMPARISON — all encoders × downstreams")
    print("=" * 100)

    display_cols = [
        "encoder", "cell",
        "dbcv", "test_silhouette", "n_clusters_test", "noise_fraction_test",
        "nber_f1", "nber_f1_legacy_maxF1", "bai_perron_f1",
        "c1_sahm_f1", "c1_cfnai_f1", "c1_chauvet_f1",
        "c3_indpro_f1", "c3_payems_f1", "c3_unrate_f1",
        "c4_ari",
    ]
    display_cols = [c for c in display_cols if c in table.columns]
    with pd.option_context("display.max_rows", 100, "display.max_columns", 30,
                           "display.width", 200, "display.float_format", "{:.3f}".format):
        print(table[display_cols].to_string(index=False))

    # ── print best-per-encoder summary ───────────────────────────────────────
    print("\n" + "=" * 80)
    print("BEST pca_kmeans per encoder (direct comparison across encoders)")
    print("=" * 80)
    km_only = table[table["cell"] == "pca_kmeans"].copy()
    print(km_only[display_cols].to_string(index=False))

    print(f"\nFull results at: {out_csv}")


if __name__ == "__main__":
    main()
