#!/usr/bin/env python3
"""Phase C locked evaluation — VAL-frozen recession-cluster assignment.

This script re-runs the Phase C evaluation under the locked protocol:
  - Recession cluster is selected on VAL (not TEST) to eliminate test-set leakage.
  - Best downstream cell is also selected on VAL.
  - C1 multi-label evaluation uses the VAL-derived assignment.

Requires embeddings (Z_train/Z_val/Z_test.parquet) to be pre-computed.
For iTransformer: results/sm_outputs/itransformer-1777581449-0d38/embeddings/
For Phase E:      results/phase_e/{enc}/embeddings/
For baselines:    results/phase_c_comparison/{enc}/emb/  (generated by run_phase_c_comparison.py)

Usage:
    cd tcc_ai
    source ../tcc.env
    uv run python scripts/run_phase_c_locked.py

Output:
    outputs/tables/phase_c_locked_all_cells.csv
    outputs/tables/phase_c_locked_best_cell.csv
    outputs/tables/phase_c_canonical_pca_kmeans.csv
    results/clustering_ablation/W6_d7_K4_b1/val_{cell}.parquet  (VAL label cache)
    results/phase_e/{enc}/ablation/val_{cell}.parquet
    results/phase_c_comparison/{enc}/val_{cell}.parquet
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from tcc_itransformer.data.external_labels import load_usrec
from tcc_itransformer.evaluation.regime_validation import (
    fit_nber_assignment,
    nber_overlap_frozen,
)
from tcc_itransformer.pipelines.clustering_ablation import (
    _cluster,
    _load_split,
    _reduce,
)
from tcc_itransformer.pipelines.multi_label import run_multi_label
from tcc_itransformer.pipelines.bai_perron_headline import run_bai_perron_headline
from tcc_itransformer.pipelines.cluster_stability import run_cluster_stability

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ── paths ────────────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
USREC_CSV = ROOT / "data/snapshots/nber_usrec.csv"
ITR_EMB_DIR = ROOT / "results/sm_outputs/itransformer-1777581449-0d38/embeddings"
ITR_ABLATION_DIR = ROOT / "results/clustering_ablation/W6_d7_K4_b1"
PHASE_E_ROOT = ROOT / "results/phase_e"
BASELINES_ROOT = ROOT / "results/phase_c_comparison"
OUT_TABLES = ROOT / "outputs/tables"
def _load_fred_key() -> str | None:
    """Load FRED_API_KEY from env or ../tcc.env fallback."""
    key = os.environ.get("FRED_API_KEY")
    if key:
        return key
    env_file = ROOT.parent / "tcc.env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip().removeprefix("export ").strip()
            if line.startswith("FRED_API_KEY="):
                key = line.split("=", 1)[1].strip().strip('"').strip("'")
                if key:
                    os.environ["FRED_API_KEY"] = key
                    return key
    return None


FRED_API_KEY = _load_fred_key()

PHASE_E_NAMES: frozenset[str] = frozenset({
    "moment", "ts2vec", "patchtst", "timesnet", "tfc", "hamilton_hmm", "bocpd",
})

BASELINE_NAMES: frozenset[str] = frozenset({
    "windowed_pca", "raw_pca", "linear_ae", "mlp_ae", "svd",
})

ALL_CELLS = [
    "pca_kmeans", "pca_hdbscan",
    "umap_kmeans", "umap_hdbscan",
    "tsne_kmeans", "tsne_hdbscan",
]


# ── helpers ──────────────────────────────────────────────────────────────────

def _emb_ablation_dirs(enc: str) -> tuple[Path, Path]:
    """Return (emb_dir, ablation_dir) for the given encoder name."""
    if enc == "iTransformer":
        return ITR_EMB_DIR, ITR_ABLATION_DIR
    if enc in PHASE_E_NAMES:
        return (
            PHASE_E_ROOT / enc / "embeddings",
            PHASE_E_ROOT / enc / "ablation",
        )
    # baseline encoder
    return (
        BASELINES_ROOT / enc / "emb",
        BASELINES_ROOT / enc,
    )


def _dr_cl_from_cell(cell: str) -> tuple[str, str]:
    """Parse 'pca_kmeans' → ('pca', 'kmeans')."""
    dr, cl = cell.rsplit("_", 1)
    return dr, cl


def _save_val_parquet(
    val_dates: pd.DatetimeIndex,
    val_labels: np.ndarray,
    Y_val: np.ndarray,
    out_path: Path,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame({
        "date": val_dates,
        "label": val_labels.astype(np.int32),
        "x_2d": Y_val[:, 0].astype(np.float32),
        "y_2d": Y_val[:, 1].astype(np.float32),
    }).to_parquet(out_path, index=False)


def compute_val_labels_for_cell(
    enc: str,
    cell: str,
    emb_dir: Path,
    ablation_dir: Path,
    seed: int = 42,
    n_clusters: int = 4,
) -> tuple[np.ndarray, pd.DatetimeIndex, np.ndarray] | None:
    """Fit downstream pipeline on TRAIN, predict VAL labels.

    Returns (val_labels, val_dates, Y_val_2d) or None on failure.
    """
    cache_path = ablation_dir / f"val_{cell}.parquet"
    if cache_path.exists():
        df = pd.read_parquet(cache_path)
        val_labels = df["label"].to_numpy()
        val_dates = pd.DatetimeIndex(df["date"])
        Y_val = df[["x_2d", "y_2d"]].to_numpy(dtype=np.float32)
        logger.info("[%s/%s] VAL labels loaded from cache (%d months)", enc, cell, len(val_labels))
        return val_labels, val_dates, Y_val

    if not emb_dir.exists() or not (emb_dir / "Z_train.parquet").exists():
        logger.warning("[%s/%s] embeddings not found at %s", enc, cell, emb_dir)
        return None

    try:
        train = _load_split(emb_dir, "train")
        val = _load_split(emb_dir, "val")
        test = _load_split(emb_dir, "test")
    except Exception as exc:
        logger.warning("[%s/%s] Failed to load embeddings: %s", enc, cell, exc)
        return None

    dr, cl = _dr_cl_from_cell(cell)
    try:
        Y_tr, Y_va, Y_te = _reduce(dr, train.Z, val.Z, test.Z, seed=seed)
        val_labels, _test_labels, _probs, _diag = _cluster(
            cl, Y_tr, Y_va, Y_te, n_clusters=n_clusters, seed=seed,
        )
    except Exception as exc:
        logger.warning("[%s/%s] DR/clustering failed: %s", enc, cell, exc)
        return None

    _save_val_parquet(val.dates, val_labels, Y_va, cache_path)
    logger.info(
        "[%s/%s] VAL labels computed: %d months, %d unique clusters",
        enc, cell, len(val_labels), len(set(val_labels.tolist()))
    )
    return val_labels, val.dates, Y_va


def run_c1_locked(
    enc: str,
    cell: str,
    ablation_dir: Path,
    assignment: dict[int, int],
) -> dict:
    """Run C1 multi-label with VAL-locked assignment. Returns flat metric dict."""
    test_parquet = ablation_dir / f"{cell}.parquet"
    if not test_parquet.exists():
        logger.warning("[%s/%s] TEST parquet not found: %s", enc, cell, test_parquet)
        return {}

    c1_out = ablation_dir / f"c1_multi_label_{cell}_locked.csv"
    ext: dict = {}
    try:
        df_c1 = run_multi_label(
            test_parquet, USREC_CSV, c1_out,
            fred_api_key=FRED_API_KEY,
            assignment=assignment,   # VAL-derived, locked
        )
        label_col = "label" if "label" in df_c1.columns else "indicator"
        indicator_map = {
            "sahm": "c1_sahm_f1",
            "cfnai_ma3": "c1_cfnai_f1",
            "chauvet_piger": "c1_chauvet_f1",
            "oecd_cli": "c1_oecd_f1",
        }
        for _, row in df_c1.iterrows():
            key = indicator_map.get(row[label_col])
            if key:
                ext[key] = round(float(row["f1"]), 4) if pd.notna(row["f1"]) else float("nan")
        # Also capture AUC (now correctly computed as cluster balanced accuracy)
        for _, row in df_c1.iterrows():
            key_auc = indicator_map.get(row[label_col], "").replace("_f1", "_auc")
            if key_auc:
                ext[key_auc] = round(float(row["auc_roc"]), 4) if pd.notna(row.get("auc_roc", float("nan"))) else float("nan")
    except Exception as exc:
        logger.warning("[%s/%s] C1 locked failed: %s", enc, cell, exc)
    return ext


def run_c3_locked(
    enc: str,
    cell: str,
    ablation_dir: Path,
) -> dict:
    """Run C3 PELT structural breaks. Returns flat metric dict.

    C3 is NOT affected by the VAL-locked assignment (measures cluster transitions
    vs. FRED structural breaks, independent of which cluster is 'recession').
    Falls back to cached c3 CSV if available and FRED pull fails.
    """
    test_parquet = ablation_dir / f"{cell}.parquet"
    if not test_parquet.exists():
        return {}

    series_map = {
        "INDPRO": "c3_indpro_f1",
        "PAYEMS": "c3_payems_f1",
        "UNRATE": "c3_unrate_f1",
    }

    def _parse_c3_df(df_c3: pd.DataFrame) -> dict:
        ext: dict = {}
        if "pelt_f1" not in df_c3.columns:
            return ext
        for _, row in df_c3.iterrows():
            key = series_map.get(row["series"])
            if key:
                val = row.get("pelt_f1", float("nan"))
                ext[key] = round(float(val), 4) if pd.notna(val) else float("nan")
        return ext

    # Try fresh run first
    c3_out = ablation_dir / f"c3_pelt_{cell}_locked.csv"
    try:
        df_c3 = run_bai_perron_headline(test_parquet, c3_out, fred_api_key=FRED_API_KEY)
        result = _parse_c3_df(df_c3)
        if result:
            return result
    except Exception as exc:
        logger.warning("[%s/%s] C3 fresh run failed (%s) — trying cached CSV", enc, cell, exc)

    # Fall back to cached c3 CSV (C3 is unaffected by the assignment-fix)
    cached = ablation_dir / f"c3_bai_perron_{cell}.csv"
    if not cached.exists():
        cached = ablation_dir / f"c3_pelt_{cell}.csv"
    if cached.exists():
        try:
            df_cached = pd.read_csv(cached)
            # Cached file may use 'bai_perron_f1' or 'pelt_f1' column name
            if "bai_perron_f1" in df_cached.columns and "pelt_f1" not in df_cached.columns:
                df_cached = df_cached.rename(columns={"bai_perron_f1": "pelt_f1"})
            result = _parse_c3_df(df_cached)
            if result:
                logger.info("[%s/%s] C3 loaded from cached CSV (%s)", enc, cell, cached.name)
                return result
        except Exception as exc2:
            logger.warning("[%s/%s] C3 cached CSV load failed: %s", enc, cell, exc2)

    return {}


def compute_val_nber_f1(
    val_labels: np.ndarray,
    val_dates: pd.DatetimeIndex,
    assignment: dict[int, int],
) -> float:
    """Compute NBER F1 on VAL using the frozen assignment (for best-cell selection)."""
    try:
        usrec = load_usrec(USREC_CSV)
        res = nber_overlap_frozen(val_labels, val_dates, usrec, assignment, lead=0, lag=2)
        return float(res.f1)
    except Exception:
        return float("nan")


def compute_val_c1_f1s(
    val_labels: np.ndarray,
    val_dates: pd.DatetimeIndex,
    assignment: dict[int, int],
) -> dict[str, float]:
    """Compute C1 F1s on VAL for best-cell selection (requires FRED API key)."""
    if not FRED_API_KEY:
        logger.warning("FRED_API_KEY not set — skipping VAL C1 metrics (NBER F1 used for cell selection)")
        return {}
    try:
        from tcc_itransformer.data.external_labels import load_all_external_labels
        from tcc_itransformer.evaluation.regime_validation import multi_label_overlap
        label_series = load_all_external_labels(api_key=FRED_API_KEY)
        df = multi_label_overlap(val_labels, val_dates, label_series, assignment)
        return {
            row["label"]: round(float(row["f1"]), 4)
            for _, row in df.iterrows()
            if pd.notna(row["f1"])
        }
    except Exception as exc:
        logger.warning("VAL C1 metrics failed: %s", exc)
        return {}


# ── main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    os.chdir(ROOT)
    OUT_TABLES.mkdir(parents=True, exist_ok=True)

    usrec = load_usrec(USREC_CSV)

    # encoder → cell → metrics dict
    all_rows: list[dict] = []

    ENCODERS = (
        ["iTransformer"]
        + sorted(PHASE_E_NAMES)
        + sorted(BASELINE_NAMES)
    )

    for enc in ENCODERS:
        emb_dir, ablation_dir = _emb_ablation_dirs(enc)
        logger.info("=" * 60)
        logger.info("ENCODER: %s | emb_dir=%s", enc, emb_dir)

        # ── per-cell: compute VAL labels + assignment ─────────────────────────
        cell_val_results: dict[str, dict] = {}   # cell → {val_labels, val_dates, assignment, val_nber_f1}

        for cell in ALL_CELLS:
            result = compute_val_labels_for_cell(enc, cell, emb_dir, ablation_dir)
            if result is None:
                logger.warning("[%s/%s] Skipping — could not compute VAL labels", enc, cell)
                continue
            val_labels, val_dates, Y_val = result

            # Derive frozen assignment on VAL (the key fix for Finding #2)
            try:
                assignment = fit_nber_assignment(val_labels, val_dates, usrec, lead=0, lag=2)
            except Exception as exc:
                logger.warning("[%s/%s] fit_nber_assignment failed: %s", enc, cell, exc)
                continue

            val_nber_f1 = compute_val_nber_f1(val_labels, val_dates, assignment)
            val_c1 = compute_val_c1_f1s(val_labels, val_dates, assignment)
            val_sahm = val_c1.get("sahm", float("nan"))
            val_cfnai = val_c1.get("cfnai_ma3", float("nan"))

            cell_val_results[cell] = {
                "val_labels": val_labels,
                "val_dates": val_dates,
                "assignment": assignment,
                "val_nber_f1": val_nber_f1,
                "val_sahm_f1": val_sahm,
                "val_cfnai_f1": val_cfnai,
            }

        if not cell_val_results:
            logger.error("[%s] No cells produced VAL labels — skipping encoder", enc)
            continue

        # ── best cell on VAL ──────────────────────────────────────────────────
        # Selection criterion: mean(NBER_F1_val, Sahm_F1_val, CFNAI_F1_val)
        # Ties broken by pca_kmeans preference.
        def cell_score(cell: str) -> float:
            r = cell_val_results.get(cell, {})
            vals = [r.get("val_nber_f1", float("nan")),
                    r.get("val_sahm_f1", float("nan")),
                    r.get("val_cfnai_f1", float("nan"))]
            valid = [v for v in vals if not np.isnan(v)]
            if not valid:
                return float("nan")
            return sum(valid) / len(valid)

        best_cell = max(cell_val_results.keys(), key=cell_score, default="pca_kmeans")
        best_score = cell_score(best_cell)
        logger.info("[%s] Best cell on VAL: %s (score=%.3f)", enc, best_cell, best_score)

        # ── per-cell: run C1/C3 with locked assignment ────────────────────────
        for cell in ALL_CELLS:
            if cell not in cell_val_results:
                continue

            assignment = cell_val_results[cell]["assignment"]
            val_nber_f1 = cell_val_results[cell]["val_nber_f1"]

            # Load existing TEST ablation summary row
            test_parquet = ablation_dir / f"{cell}.parquet"
            if not test_parquet.exists():
                logger.warning("[%s/%s] TEST parquet missing, skipping", enc, cell)
                continue

            # Recompute TEST NBER F1 with locked assignment
            test_df = pd.read_parquet(test_parquet)
            test_labels = test_df["label"].to_numpy()
            test_dates = pd.DatetimeIndex(test_df["date"])
            try:
                test_res = nber_overlap_frozen(test_labels, test_dates, usrec, assignment)
                test_nber_f1 = round(float(test_res.f1), 4)
                test_nber_prec = round(float(test_res.precision), 4)
                test_nber_recall = round(float(test_res.recall), 4)
            except Exception as exc:
                logger.warning("[%s/%s] nber_overlap_frozen failed: %s", enc, cell, exc)
                test_nber_f1 = test_nber_prec = test_nber_recall = float("nan")

            # Read existing ablation metrics (DBCV, silhouette, etc.)
            existing_summary_csv = ablation_dir / "summary.csv"
            dbcv = sil = n_cl = noise_frac = float("nan")
            if existing_summary_csv.exists():
                summ = pd.read_csv(existing_summary_csv)
                row_match = summ[summ["cell"] == cell]
                if not row_match.empty:
                    r = row_match.iloc[0]
                    dbcv = float(r.get("dbcv", float("nan"))) if pd.notna(r.get("dbcv", float("nan"))) else float("nan")
                    sil = float(r.get("test_silhouette", float("nan"))) if pd.notna(r.get("test_silhouette", float("nan"))) else float("nan")
                    n_cl = float(r.get("n_clusters_test", float("nan")))
                    noise_frac = float(r.get("noise_fraction_test", float("nan")))

            # C1 locked
            c1_metrics = run_c1_locked(enc, cell, ablation_dir, assignment)

            # C3 (PELT — not affected by selection rule, but run with correct label)
            c3_metrics = run_c3_locked(enc, cell, ablation_dir)

            # C4: use cached ARI from c4_stability.csv
            c4_ari = float("nan")
            c4_csv = ablation_dir / "c4_stability.csv"
            if c4_csv.exists():
                c4_df = pd.read_csv(c4_csv)
                c4_row = c4_df[(c4_df["pipeline"] == cell) & (c4_df["cluster"] == "all") & (c4_df["metric"] == "ari")]
                if not c4_row.empty:
                    c4_ari = round(float(c4_row.iloc[0]["mean_value"]), 4)

            row = {
                "encoder": enc,
                "cell": cell,
                "is_best_cell_on_val": (cell == best_cell),
                "val_nber_f1": round(val_nber_f1, 4) if not np.isnan(val_nber_f1) else float("nan"),
                "val_sahm_f1": round(cell_val_results[cell]["val_sahm_f1"], 4) if not np.isnan(cell_val_results[cell]["val_sahm_f1"]) else float("nan"),
                "val_cfnai_f1": round(cell_val_results[cell]["val_cfnai_f1"], 4) if not np.isnan(cell_val_results[cell]["val_cfnai_f1"]) else float("nan"),
                "nber_assignment": str(assignment),
                "dbcv": dbcv,
                "test_silhouette": sil,
                "n_clusters_test": n_cl,
                "noise_fraction_test": noise_frac,
                "nber_f1_locked": test_nber_f1,           # KEY: locked assignment
                "nber_precision_locked": test_nber_prec,
                "nber_recall_locked": test_nber_recall,
                **{k: v for k, v in c1_metrics.items()},
                **{k: v for k, v in c3_metrics.items()},
                "c4_ari": c4_ari,
            }
            all_rows.append(row)

    if not all_rows:
        logger.error("No rows generated. Check that embeddings and ablation parquets exist.")
        sys.exit(1)

    df = pd.DataFrame(all_rows)

    # Round floats
    float_cols = df.select_dtypes(include=[float]).columns
    df[float_cols] = df[float_cols].round(4)

    # Sort
    encoder_order = {
        "iTransformer": 0, "windowed_pca": 1, "raw_pca": 2,
        "linear_ae": 3, "mlp_ae": 4, "svd": 5,
        "bocpd": 6, "hamilton_hmm": 7, "moment": 8, "patchtst": 9,
        "tfc": 10, "timesnet": 11, "ts2vec": 12,
    }
    cell_order = {
        "pca_kmeans": 0, "pca_hdbscan": 1,
        "umap_kmeans": 2, "umap_hdbscan": 3,
        "tsne_kmeans": 4, "tsne_hdbscan": 5,
    }
    df["_eo"] = df["encoder"].map(encoder_order).fillna(99)
    df["_co"] = df["cell"].map(cell_order).fillna(9)
    df = df.sort_values(["_eo", "_co"]).drop(columns=["_eo", "_co"]).reset_index(drop=True)

    # ── write output tables ───────────────────────────────────────────────────
    # 1. Full locked table (all encoders × all cells)
    out_all = OUT_TABLES / "phase_c_locked_all_cells.csv"
    df.to_csv(out_all, index=False)
    logger.info("Full locked table: %s", out_all)

    # 2. Best-cell per encoder (VAL-selected)
    best_df = df[df["is_best_cell_on_val"] == True].copy()
    out_best = OUT_TABLES / "phase_c_locked_best_cell.csv"
    best_df.to_csv(out_best, index=False)
    logger.info("Best-cell table: %s", out_best)

    # 3. Canonical pca_kmeans only (direct comparison row)
    km_df = df[df["cell"] == "pca_kmeans"].copy()
    out_km = OUT_TABLES / "phase_c_canonical_pca_kmeans.csv"
    km_df.to_csv(out_km, index=False)
    logger.info("Canonical pca_kmeans table: %s", out_km)

    # ── print summary ─────────────────────────────────────────────────────────
    print("\n" + "=" * 100)
    print("PHASE C — LOCKED PROTOCOL (VAL-frozen assignment)")
    print("=" * 100)

    display_cols = [
        "encoder", "cell", "is_best_cell_on_val",
        "val_nber_f1",
        "nber_f1_locked", "dbcv", "test_silhouette",
        "c1_sahm_f1", "c1_cfnai_f1", "c1_chauvet_f1",
        "c3_indpro_f1", "c3_payems_f1", "c4_ari",
    ]
    display_cols = [c for c in display_cols if c in df.columns]
    with pd.option_context(
        "display.max_rows", 120, "display.max_columns", 30,
        "display.width", 200, "display.float_format", "{:.3f}".format
    ):
        print(df[display_cols].to_string(index=False))

    print(f"\nFull results written to: {OUT_TABLES}")


if __name__ == "__main__":
    main()
